version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: estoque_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: projetoitamar
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  mysql_data: